language: r
sudo: false
cache: packages
git:
  depth: false
apt_packages:
  - libpoppler-cpp-dev
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
