# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

requirements:
  build:
    - r
    - r-RCurl
  run:
    - r
    - r-RCurl

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
